pipeline:
  name: DevSecOps
  identifier: DevSecOps
  projectIdentifier: DevSecOps
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1691491451111
        repoName: DevSecOps_POC
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: npm_install
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: npm install
                isAnyParentContainerStepGroup: false
              - step:
                  identifier: npm_test
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: npm_build
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: npm run build
