name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_separate_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Use the PAT
        run: echo ${{ secrets.DEPLOYMENT_PAT }}
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: List directory
        run: ls

      - name: Create separate branch
        run: |
          git checkout -b main_clone
          ls
          git push origin main_clone

  deploy:
    runs-on: ubuntu-latest
    needs: [create_separate_branch]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "jeeva.e@avasoft.com"
          git config --global user.name "Ava-JeevaYovanE"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create File
        run: |
          echo "This is some content." > new_file12.txt
          git add new_file12.txt
          git commit -m "Add new_file3.txt"
          git push origin main
      - name: Build
        run: |
          echo "Build"
      - name: Deploy
        run: |
          echo "Deploy"
          exit 1

  Deploy_check:
    runs-on: ubuntu-latest
    needs: [deploy, create_separate_branch]
    if: failure()
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email "bhagyalakshmi.c@avasoft.com"
          git config --global user.name "Ava-Bhagya"
      - name: Commands
        run: |
          git remote -v 
          git remote rm origin
          git remote add origin https://github.com/POC-DevSecOps/DevSecOps_POC.git
          git push --set-upstream -f origin main
          git checkout main
          git fetch --all
          ls
          git merge --ff origin/main_clone --allow-unrelated-histories
          git push origin main
